/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

import { AnalysisResult, CADDesign } from '../shared/types';
import { FileText, Download, CheckCircle, AlertTriangle, Star } from 'lucide-react';
import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';

interface Props {
  analysis: AnalysisResult;
  design: CADDesign;
  onClose: () => void;
}

export function ReportView({ analysis, design, onClose }: Props) {
  const exportPDF = async () => {
    const doc = new jsPDF();
    const element = document.getElementById('report-content');
    if (!element) return;

    const canvas = await html2canvas(element, {
      scale: 2,
      backgroundColor: '#000000',
      logging: false,
    });

    const imgData = canvas.toDataURL('image/png');
    const imgWidth = 190;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    doc.setFillColor(0, 0, 0);
    doc.rect(0, 0, 210, 297, 'F');
    doc.addImage(imgData, 'PNG', 10, 10, imgWidth, imgHeight);
    doc.save(`${design.name.replace(/\s+/g, '_')}_Report.pdf`);
  };

  return (
    <div className="absolute inset-0 z-50 bg-black/90 backdrop-blur-xl flex items-center justify-center p-8 overflow-y-auto">
      <div className="w-full max-w-4xl bg-[#0a0a0a] border border-white/10 rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh]">
        <div className="p-8 border-b border-white/10 flex items-center justify-between bg-white/5">
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 bg-white text-black rounded-xl flex items-center justify-center">
              <FileText className="w-6 h-6" />
            </div>
            <div>
              <h2 className="text-2xl font-bold text-white italic font-serif">Design Analysis Report</h2>
              <p className="text-xs text-white/40 font-mono uppercase tracking-widest">Generated by Gemini AI Engine</p>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <button
              onClick={exportPDF}
              className="px-6 py-3 bg-white text-black rounded-lg font-bold text-xs uppercase tracking-widest hover:bg-white/90 transition-all flex items-center gap-2"
            >
              <Download className="w-4 h-4" />
              Download PDF
            </button>
            <button
              onClick={onClose}
              className="px-6 py-3 bg-white/5 text-white/60 rounded-lg font-bold text-xs uppercase tracking-widest hover:bg-white/10 transition-all"
            >
              Close
            </button>
          </div>
        </div>

        <div id="report-content" className="p-12 space-y-12 overflow-y-auto text-white">
          <div className="grid grid-cols-3 gap-8">
            <div className="p-6 bg-white/5 border border-white/10 rounded-xl flex flex-col items-center justify-center text-center">
              <div className="text-4xl font-bold mb-2 font-serif italic">{analysis.score}</div>
              <div className="text-[10px] uppercase tracking-widest opacity-50 font-mono">Overall Score</div>
            </div>
            <div className="p-6 bg-white/5 border border-white/10 rounded-xl flex flex-col items-center justify-center text-center">
              <div className="flex items-center gap-2 mb-2">
                <CheckCircle className={`w-6 h-6 ${analysis.structuralIntegrity === 'High' ? 'text-green-400' : analysis.structuralIntegrity === 'Medium' ? 'text-yellow-400' : 'text-red-400'}`} />
                <span className="text-xl font-bold">{analysis.structuralIntegrity}</span>
              </div>
              <div className="text-[10px] uppercase tracking-widest opacity-50 font-mono">Structural Integrity</div>
            </div>
            <div className="p-6 bg-white/5 border border-white/10 rounded-xl flex flex-col items-center justify-center text-center">
              <div className="flex items-center gap-1 mb-2">
                {[...Array(5)].map((_, i) => (
                  <Star key={i} className={`w-5 h-5 ${i < analysis.aestheticRating ? 'text-yellow-400 fill-current' : 'text-white/10'}`} />
                ))}
              </div>
              <div className="text-[10px] uppercase tracking-widest opacity-50 font-mono">Aesthetic Rating</div>
            </div>
          </div>

          <section className="space-y-4">
            <h3 className="text-sm font-mono uppercase tracking-[0.2em] text-white/40 border-b border-white/10 pb-2">Executive Summary</h3>
            <p className="text-lg leading-relaxed text-white/80 italic font-serif">{analysis.summary}</p>
          </section>

          <section className="space-y-6">
            <h3 className="text-sm font-mono uppercase tracking-[0.2em] text-white/40 border-b border-white/10 pb-2">Optimization Suggestions</h3>
            <div className="grid gap-4">
              {analysis.suggestions.map((suggestion, i) => (
                <div key={i} className="flex gap-4 p-4 bg-white/5 border border-white/5 rounded-lg items-start">
                  <div className="w-6 h-6 bg-white/10 rounded-full flex items-center justify-center text-[10px] font-mono shrink-0">{i + 1}</div>
                  <p className="text-sm text-white/70 leading-relaxed">{suggestion}</p>
                </div>
              ))}
            </div>
          </section>

          <section className="space-y-4">
            <h3 className="text-sm font-mono uppercase tracking-[0.2em] text-white/40 border-b border-white/10 pb-2">Scene Metadata</h3>
            <div className="grid grid-cols-2 gap-4">
              <div className="p-4 bg-white/5 rounded-lg flex justify-between items-center">
                <span className="text-[10px] uppercase tracking-widest opacity-40">Total Elements</span>
                <span className="text-sm font-mono">{design.elements.length}</span>
              </div>
              <div className="p-4 bg-white/5 rounded-lg flex justify-between items-center">
                <span className="text-[10px] uppercase tracking-widest opacity-40">Timestamp</span>
                <span className="text-sm font-mono">{new Date().toLocaleTimeString()}</span>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}
